### ISSUE TITLE
Forgets temperature after setting brightness too high

### ISSUE THREAD

**Issue by cjmanca** [gfrancesco/cwww-template-light-ha#4]
Currently, it's changing the stored number helper values based on the calculations. This means that when you go above 50% brightness, it starts clamping the temperature, and this is stored, so when you reduce the brightness again, it's not the same temperature it was before increasing the brightness.

I think a good solution to this would be to store the "desired" brightness/temperature rather than the result of the calculations, and do the calculations in local variables while setting the actual shelly lines.

**Comment by gfrancesco** [comment]
That will likely break the template light. The helpers are used to drive the dashboard card and the state of the entity, they cannot be replaced by something else.
Storing a "desired" value will also put the light in an inconsistent state, since the combination is outside the region the light can reach. Given a pair of temperature and brightness there is no way for the light to know if it should keep the temperature and adapt the brightness or vice versa. The choice is arbitrary.

My suggestion is to leave the template as it is, and add a scene or an automation do handle transitions or specific states. A scene might not work as you expect though, bear that in mind if you try.
